# Generated by Django 5.0.7 on 2024-08-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_name', models.CharField(max_length=100)),
                ('Recipe_description', models.TextField()),
                ('Recipe_Ingrediants', models.TextField()),
                ('Recipe_Image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
