# Generated by Django 5.0.7 on 2024-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recipe_name', models.CharField(max_length=100)),
                ('Recipe_description', models.TextField()),
                ('Recipe_Ingrediants', models.TextField()),
                ('Recipe_Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
