# Generated by Django 5.0.7 on 2024-08-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='recipe',
            new_name='Recipes',
        ),
    ]
