# Generated by Django 5.0.7 on 2024-08-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_remove_recipes_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='Recipe_Ingrediants',
        ),
    ]
