# Generated by Django 5.0.7 on 2024-08-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_remove_recipes_recipe_ingrediants'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='Recipe_Image',
            field=models.ImageField(default='asda', upload_to='images/'),
            preserve_default=False,
        ),
    ]
